docs_dir: docs/book
site_dir: docs/html
nav:
  - Home: index.md
  - Introduction: intro.md
  - 'Quick Start': quick-start.md
  - Reference:
      - 'Dynamic Fields': dynamic-fields.md
      - Examples: examples.md
site_name: oneplace-skeleton
site_description: "onePlace Application Skeleton Module"
repo_url: 'https://github.com/OnePlc/PLC_X_Skeleton'
theme: readthedocs
extra:
  project: onePlc